"""added is technician column

Revision ID: 5d5acf81882d
Revises: 5537a9f22690
Create Date: 2022-06-25 12:01:19.069612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5acf81882d'
down_revision = '5537a9f22690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_technician', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_technician')
    # ### end Alembic commands ###
