"""added resolution column

Revision ID: 7246223fc421
Revises: 5d5acf81882d
Create Date: 2022-06-29 22:39:58.301362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7246223fc421'
down_revision = '5d5acf81882d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('tech_resolution', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'tech_resolution')
    # ### end Alembic commands ###
